name: 1 - Workflow connexion Azure # Nom du Workflow

on:
  workflow_dispatch: # manuel https://docs.github.com/en/actions/using-workflows/triggering-a-workflow

jobs:
  
  connexion-azure: # Nom du job   
    runs-on: self-hosted # Runner machine qui execute le workflow https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners

    
    steps:
      
      - name: connexion Azure
        uses: Azure/login@v1 # Action pour se connecter à Azure https://github.com/Azure/login
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }} # Service Secrets de GitHub https://docs.github.com/en/actions/security-guides/encrypted-secrets

      - name: Liste des ressources groupes dans un abonnement
        run: |
          az group list -o table
